"use client"

import { useState, useEffect } from "react"
import { Copy, Check, Download, Filter } from "lucide-react"
import { cn } from "@/lib/utils"

interface TeamMemberReport {
  userId: string
  userName: string
  totalHours: number
  entriesCount: number
  entries: Array<{
    id: string
    client: string
    sprint: string
    task: string
    hours: number
    description: string
  }>
}

interface TeamWorkViewProps {
  date: string
}

export function TeamWorkView({ date }: TeamWorkViewProps) {
  const [reports, setReports] = useState<TeamMemberReport[]>([])
  const [loading, setLoading] = useState(true)
  const [copiedKey, setCopiedKey] = useState<string | null>(null)
  const [groupBy, setGroupBy] = useState<"member" | "client" | "sprint">("member")

  useEffect(() => {
    const fetchTeamReports = async () => {
      try {
        const token = localStorage.getItem("sessionToken")
        const response = await fetch(`/api/reports/team?date=${date}`, {
          headers: token ? { Authorization: `Bearer ${token}` } : {},
        })
        if (response.ok) {
          const data = await response.json()
          setReports(data.reports || [])
        }
      } catch (error) {
        console.error("[v0] Failed to fetch team reports:", error)
      } finally {
        setLoading(false)
      }
    }

    fetchTeamReports()
  }, [date])

  const totalTeamHours = reports.reduce((sum, r) => sum + r.totalHours, 0)
  const totalEntries = reports.reduce((sum, r) => sum + r.entriesCount, 0)

  const buildGroupedSummary = () => {
    if (groupBy === "member") {
      return reports.map(member => ({
        label: member.userName,
        hours: member.totalHours,
        items: member.entries,
        icon: "👤",
      }))
    } else if (groupBy === "client") {
      const byClient: Record<string, typeof reports[0]["entries"]> = {}
      reports.forEach(member => {
        member.entries.forEach(entry => {
          if (!byClient[entry.client]) byClient[entry.client] = []
          byClient[entry.client].push(entry)
        })
      })
      return Object.entries(byClient).map(([clientName, entries]) => ({
        label: clientName,
        hours: entries.reduce((s, e) => s + e.hours, 0),
        items: entries,
        icon: "🏢",
      }))
    } else {
      const bySprint: Record<string, typeof reports[0]["entries"]> = {}
      reports.forEach(member => {
        member.entries.forEach(entry => {
          if (!bySprint[entry.sprint]) bySprint[entry.sprint] = []
          bySprint[entry.sprint].push(entry)
        })
      })
      return Object.entries(bySprint).map(([sprintName, entries]) => ({
        label: sprintName,
        hours: entries.reduce((s, e) => s + e.hours, 0),
        items: entries,
        icon: "🎯",
      }))
    }
  }

  const buildCopyText = () => {
    const lines = []
    lines.push(`📊 Team Work Summary — ${date}`)
    lines.push(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`)
    lines.push(``)
    lines.push(`Total Hours: ${totalTeamHours.toFixed(1)}h  |  Entries: ${totalEntries}`)
    lines.push(``)

    if (groupBy === "member") {
      reports.forEach(member => {
        if (member.totalHours === 0) return
        lines.push(`👤 ${member.userName} — ${member.totalHours.toFixed(1)}h`)
        member.entries.forEach(entry => {
          lines.push(`   • ${entry.task} (${entry.client}) | ${entry.hours}h`)
          if (entry.description) lines.push(`     ${entry.description}`)
        })
        lines.push(``)
      })
    } else {
      const grouped = buildGroupedSummary()
      grouped.forEach(group => {
        lines.push(`${group.icon} ${group.label} — ${group.hours.toFixed(1)}h`)
        group.items.forEach(entry => {
          lines.push(`   • ${entry.task} | ${entry.hours}h`)
        })
        lines.push(``)
      })
    }

    lines.push(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`)
    lines.push(`Generated by StoryOps • ${new Date().toLocaleTimeString()}`)
    return lines.join("\n")
  }

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text)
    setCopiedKey("summary")
    setTimeout(() => setCopiedKey(null), 2000)
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="animate-spin">
          <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full" />
        </div>
      </div>
    )
  }

  if (reports.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-96 rounded-2xl border-2 border-dashed border-border bg-muted/30">
        <div className="text-5xl mb-3">👥</div>
        <p className="type-h2 text-foreground mb-1">No team reports yet</p>
        <p className="type-caption">Team members haven't submitted their daily reports for this day</p>
      </div>
    )
  }

  const groupedData = buildGroupedSummary()

  return (
    <div className="space-y-6">
      {/* Hero Section */}
      <div className="rounded-2xl bg-card border border-border p-8">
        <div className="flex items-end justify-between mb-6">
          <div>
            <div className="flex items-baseline gap-3 mb-2">
              <div className="text-5xl font-black text-foreground">{totalTeamHours.toFixed(1)}</div>
              <div className="type-caption">team hours</div>
            </div>
            <p className="type-caption">
              {reports.length} {reports.length === 1 ? "team member" : "team members"} • {totalEntries} entries
            </p>
          </div>
          <button
            onClick={() => copyToClipboard(buildCopyText())}
            className={cn(
              "flex items-center gap-2 px-4 py-2.5 rounded-lg font-medium transition-all",
              copiedKey === "summary"
                ? "bg-success/10 text-success"
                : "bg-primary/10 text-primary hover:bg-primary/20"
            )}
          >
            {copiedKey === "summary" ? (
              <>
                <Check className="w-4 h-4" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                Copy Summary
              </>
            )}
          </button>
        </div>

        {/* View Toggle */}
        <div className="flex items-center gap-2 bg-muted rounded-lg p-1 w-fit">
          {(["member", "client", "sprint"] as const).map(view => (
            <button
              key={view}
              onClick={() => setGroupBy(view)}
              className={cn(
                "px-3 py-1.5 text-xs font-semibold rounded-md transition-all capitalize",
                groupBy === view
                  ? "bg-card text-foreground shadow-sm"
                  : "text-muted-foreground hover:text-foreground"
              )}
            >
              {view}
            </button>
          ))}
        </div>
      </div>

      {/* Team Members / Groups */}
      <div className="space-y-4">
        {groupedData.map((group, idx) => (
          <div key={`${groupBy}-${idx}`} className="rounded-xl bg-card border border-border overflow-hidden hover:border-primary/30 transition-colors">
            {/* Group Header */}
            <div className="flex items-center justify-between px-6 py-4 border-b border-border bg-muted/30">
              <div className="flex items-center gap-3">
                <span className="text-xl">{group.icon}</span>
                <div>
                  <p className="type-h2 text-foreground">{group.label}</p>
                  <p className="type-caption">{group.items.length} entries</p>
                </div>
              </div>
              <div className="text-right">
                <div className="type-h2 text-primary">{group.hours.toFixed(1)}</div>
                <p className="type-caption">hours</p>
              </div>
            </div>

            {/* Entries */}
            <div className="divide-y divide-border">
              {group.items.map((entry, entryIdx) => (
                <div key={`${groupBy}-${idx}-${entryIdx}`} className="px-6 py-4 hover:bg-muted/50 transition-colors">
                  <div className="flex items-start justify-between mb-2">
                    <div className="flex-1">
                      <p className="font-semibold text-foreground text-sm">{entry.task}</p>
                      <p className="type-caption mt-1">
                        {groupBy !== "client" && <span>{entry.client} • </span>}
                        {groupBy !== "sprint" && <span>{entry.sprint}</span>}
                      </p>
                    </div>
                    <div className="text-right ml-4 shrink-0">
                      <div className="font-bold text-primary text-sm">{entry.hours}h</div>
                    </div>
                  </div>
                  {entry.description && (
                    <p className="text-xs text-muted-foreground leading-relaxed mt-2">{entry.description}</p>
                  )}
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
